apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cocalc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      type: cocalc