apiVersion: v1
kind: PersistentVolume
metadata:
  name: cocalc-pv
  labels:
    type: cocalc
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/hdd/nfs/storage/cocalc
    server: nodenfs
